apiVersion: apps/v1
kind: Deployment
metadata:
  name: preit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preit
  template:
    metadata:
      labels:
        app: preit
    spec:
      containers:
      - image: okteto.dev/preit:latest
        name: preit
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.azmovies.net"
        - name: Vless_UUID
          value: "92dcc623-9d38-42bd-91c0-6f50ac51fdd6"
        - name: Vless_Path
          value: "/NPF435ry"
        - name: Vmess_UUID
          value: "92dcc623-9d38-42bd-91c0-6f50ac51fdd6"
        - name: Vmess_Path
          value: "/gu94dsf"
        - name: Share_Path
          value: "/Share581"
