apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yoit
  template:
    metadata:
      labels:
        app: yoit
    spec:
      containers:
      - image: okteto.dev/yoit:latest
        name: yoit
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mp3-juice.com"
        - name: Vless_UUID
          value: "c808c3f3-1149-4f5c-915f-f305514eb96e"
        - name: Vless_Path
          value: "/HqaGY6"
        - name: Vmess_UUID
          value: "c808c3f3-1149-4f5c-915f-f305514eb96e"
        - name: Vmess_Path
          value: "/oped7ty"
        - name: Share_Path
          value: "/Share267"
