apiVersion: apps/v1
kind: Deployment
metadata:
  name: head
spec:
  replicas: 1
  selector:
    matchLabels:
      app: head
  template:
    metadata:
      labels:
        app: head
    spec:
      containers:
      - image: okteto.dev/head:latest
        name: head
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.freemusicarchive.org"
        - name: Vless_UUID
          value: "78f3989a-486f-4e18-8eca-7852f1351e7b"
        - name: Vless_Path
          value: "/sguw4q"
        - name: Vmess_UUID
          value: "78f3989a-486f-4e18-8eca-7852f1351e7b"
        - name: Vmess_Path
          value: "/CSZX6E"
        - name: Share_Path
          value: "/Share406"
