apiVersion: apps/v1
kind: Deployment
metadata:
  name: bore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bore
  template:
    metadata:
      labels:
        app: bore
    spec:
      containers:
      - image: okteto.dev/bore:latest
        name: bore
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.jamendo.com"
        - name: Vless_UUID
          value: "3cbd6530-ea59-406f-83cb-66ff0c3c8bf8"
        - name: Vless_Path
          value: "/hkolper"
        - name: Vmess_UUID
          value: "3cbd6530-ea59-406f-83cb-66ff0c3c8bf8"
        - name: Vmess_Path
          value: "/fvDFGM"
        - name: Share_Path
          value: "/Share310"
