apiVersion: apps/v1
kind: Deployment
metadata:
  name: haru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haru
  template:
    metadata:
      labels:
        app: haru
    spec:
      containers:
      - image: okteto.dev/haru:latest
        name: haru
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "animefrenzy.net"
        - name: Vless_UUID
          value: "4860981a-ff88-4357-ae85-8526373c36ee"
        - name: Vless_Path
          value: "/WCdt6u9"
        - name: Vmess_UUID
          value: "4860981a-ff88-4357-ae85-8526373c36ee"
        - name: Vmess_Path
          value: "/gbFer8u"
        - name: Share_Path
          value: "/Share426"
